### PR TITLE
Feature/zod parser tests

### PR DESCRIPTION
**Pull request by helt**
Added a few repro tests for zod code generation.

I hope the tests make sense and are okay.

### CODE REVIEW

**Comment by helt** [comment]
The failing test complains about 
```
SyntaxError: /home/runner/work/kubb/kubb/packages/swagger-zod/mocks/zod_parser.yaml is not a valid Openapi API definition
```
However, I tried multiple validators and none complains...

**Comment by stijnvanhulle** [comment]
@helt Is this related to your issue? https://github.com/kubb-project/kubb/issues/658

**Comment by helt** [comment]
@stijnvanhulle Yes. Sorry for the intermixing of issues here. 

The tests document the following discoveries:
* `.nullable()` is added incorrectly (E. G. In test `NullableStringWithAnyOf`
* format UUID seems not to be added at all. See `NullableStringUuid`
* `const ` keyword should be translated to `z.literal(...)` if I understand correctly. Eg `NumberValueConst` test

But please note, that the expected values of the tests are merely what I think it should be, and have been written manually, and therefore might contain syntax and semantic errors!

**Comment by stijnvanhulle** [comment]
@helt Added your tests to https://github.com/kubb-project/kubb/pull/683 and also fixed the issue :)

**Pull request closed without merging**
