### PR TITLE
docs: escape curly braces

### PR DESCRIPTION
**Pull request by WickyNilliams**
noticed that some curly braces were causing blank text in the docs. i haven't tested this (apologies), but i assume escaping them should fix

### CODE REVIEW

**Comment by WickyNilliams** [comment]
ok, first time didn't work. so i actually looked at the vitepress docs then. now the braces are escaped https://kubb-git-fork-wickynilliams-patch-1-kubb.vercel.app/plugins/swagger-client/#output-1

**Comment by stijnvanhulle** [comment]
@all-contributors please add @WickyNilliams for docs

**Comment by stijnvanhulle** [comment]
@WickyNilliams Great, thanks for changing this!

**Review by stijnvanhulle — APPROVED** [review]

**Comment by WickyNilliams** [comment]
@stijnvanhulle no worries! i got quite confused reading the docs trying to work out how to use some options because of the empty text. happy to fix, so the next person doesn't face the same

**Pull request merged**
